version: '3.9'

services:
  wordpress:
    image: wordpress:fpm-alpine
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: examplepassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 30718008
    volumes:
      - ./db:/var/lib/mysql

   nginx:
    image: nginx
    restart: always
    ports:
      - "mustafatufekci.me:80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt:/etc/letsencrypt
      - ./www:/var/www/html

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./www:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email youremail@example.com --agree-tos --no-eff-email --force-renewal -d mustafatufekci.me